export const estimatedDurations = [
    {value: "",
    text: "Без длительности"},
    {value: 5,
    text: "5 минут"},
    {value: 15,
    text: "15 минут"},
    {value: 30,
    text: "30 минут"},
    {value: 60,
    text: "1 час"},
    {value: 120,
    text: "2 часа"},
    {value: 180,
    text: "3 часа"},
    {value: 300,
    text: "Полдня (5 часов)"},
    {value: 600,
    text: "Целый день (10 часов)"},
]